[tool.poetry]
name = "release_notifier"
version = "0.1.0"
description = ""
authors = ["kimihiro_n"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
